management:
  endpoints:
    web:
      exposure:
        include: health, info, restart
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

server:
  port: 8080

spring:
  application:
    name: keyword-calculator
  webflux:
    base-path: /keyword-calculator

api:
  amazon:
    auto-complete:
      url: "https://completion.amazon.com/search/complete"